api/src/models/stocks/views.py
from flask import Blueprint, render_template, request, redirect, url_for, json

from src.common.database import Database
from src.models.stocks.stock import Stock
import src.models.users.decorators as user_decorators

stock_blueprint = Blueprint('stocks', __name__)


@stock_blueprint.route('/')
def index():    # Views list of available/stored stocks
    stocks = Stock.all()
    return render_template('stocks/stock_index.jinja2', stocks=stocks)


@stock_blueprint.route('/stock/<string:stock_ticker>')
def stock_page(stock_ticker):   # Renders unique stock page
    stock = Stock.get_by_ticker(stock_ticker)
    return render_template('stocks/stock.jinja2', stock=stock)


@stock_blueprint.route('/getweights/<string:email>')
def get_weights(email):   # Renders unique stock page
    stock = Stock.get_by_ticker(stock_ticker)
    return render_template('stocks/stock.jinja2', stock=stock)


@stock_blueprint.route('/new', methods=['GET', 'POST'])
def create_stock():

    if request.method == 'POST':
        pass

    return render_template('stocks/new_stock.jinja2')


@stock_blueprint.route('/delete/<string:stock_id>', methods=['GET'])
def delete_stock(stock_id):
    Stock.get_by_ticker(stock_id).remove()

    return redirect(url_for('.index'))

api/src/models/users/views.py
from flask import Blueprint, request, session, redirect, url_for, render_template, jsonify
from src.models.users.user import User
import src.models.users.errors as UserErrors
import src.models.users.decorators as user_decorators

user_blueprint = Blueprint("users", __name__)


@user_blueprint.route("/login", methods=["GET", "POST"])
def login_user():  # Views form required for user login
    if request.method == "POST":
        # email = request.form["email"]
        # password = request.form["password"]
        email = request.get_json().get('email')
        password = request.get_json().get("password")
        try:
            if User.is_login_valid(email, password):
                return(jsonify({'Status': 'found'}))

        except UserErrors.UserError as e:
            e = str(e)
            return(jsonify({'Status': e}))

    return jsonify({'Status': 'error use POST request'})


@user_blueprint.route("/register", methods=["GET", "POST"])
def register_user():  # Views form required for user signup
    if request.method == "POST":
        email = request.get_json().get('email')
        password = request.get_json().get("password")
        try:
            if User.register_user(email, password):
                return (jsonify({'Status': 'registered'}))
        except UserErrors.UserError as e:
            e = str(e)
            return (jsonify({'Status': e}))

    return jsonify({'Status': 'error use POST request'})


@user_blueprint.route("/logout")
def logout_user():  # Logs user out
    session["email"] = None
    return redirect(url_for("home"))


# @user_blueprint.route("/portfolios")
# @user_decorators.requires_login
# def user_portfolios():  # Views list of user portfolios
#     print('1',session["email"])
#     user = User.find_by_email(session["email"])
#     portfolios = user.get_portfolios()

#     return render_template("/users/portfolios.jinja2", portfolios=portfolios)

api/src/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Basic MVO</title>

    {% include "html_dependencies.html" %}

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbar_right" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container">
        <div class="collapse navbar-collapse" id="navbar">
            <a class="navbar-brand" href="/" title="Home">MVO</a>
            <ul class="nav navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('stocks.index') }}">Stocks</a>
                </li>

            </ul>
        </div>
      {% if session['email'] %}
          <div class="collapse navbar-collapse justify-content-end" id="navbar">

              <ul class="nav navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.user_portfolios') }}">Your Portfolios</a>
                </li>
              </ul>
              <a class="btn btn-primary" href="{{ url_for('users.logout_user') }}" role="button">Log Out</a>
          </div>
      {% else %}
          <div class="collapse navbar-collapse justify-content-end" id="navbar">
              <a class="btn btn-primary" href="{{ url_for('users.register_user') }}" role="button">Sign up</a>
              <ul class="nav navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.login_user') }}">Login</a>
                </li>
              </ul>
          </div>
      {% endif %}
    </div>
</nav>

<div class="content container">
    {% block content %}

    {% endblock%}
</div>

</body>
</html>

api/src/templates/home.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-3">Basic MVO</h1>
        <p>Given a choice between three risk appetites, this application runs a simple Mean variance Optimization and
            returns the optimal portfolio. Note: All portfolios contain the same 5 assets which can be found under
            <strong>Stocks</strong> in the navigation bar above.</p>
        <p>Just sign up, set your risk appetite, and we'll do the rest!</p>
        {% if session['email'] %}
            <p class="lead">
                <a class="btn btn-primary btn-lg" href="{{ url_for('users.logout_user') }}" role="button">Log Out</a>
            </p>
        {% else %}
            <p class="lead">
                <a class="btn btn-primary btn-lg" href="{{ url_for('users.register_user') }}" role="button">Sign up</a>
            </p>
        {% endif %}
    </div>
{% endblock %}

api/src/templates/html_dependencies.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/style.css') }}"/>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>