api/src/models/stocks/views.py
from flask import Blueprint, render_template, request, redirect, url_for, json

from src.common.database import Database
from src.models.stocks.stock import Stock
import src.models.users.decorators as user_decorators

stock_blueprint = Blueprint('stocks', __name__)


@stock_blueprint.route('/')
def index():    # Views list of available/stored stocks
    stocks = Stock.all()
    return render_template('stocks/stock_index.jinja2', stocks=stocks)


@stock_blueprint.route('/stock/<string:stock_ticker>')
def stock_page(stock_ticker):   # Renders unique stock page
    stock = Stock.get_by_ticker(stock_ticker)
    return render_template('stocks/stock.jinja2', stock=stock)


@stock_blueprint.route('/getweights/<string:email>')
def get_weights(email):   # Renders unique stock page
    stock = Stock.get_by_ticker(stock_ticker)
    return render_template('stocks/stock.jinja2', stock=stock)


@stock_blueprint.route('/new', methods=['GET', 'POST'])
def create_stock():

    if request.method == 'POST':
        pass

    return render_template('stocks/new_stock.jinja2')


@stock_blueprint.route('/delete/<string:stock_id>', methods=['GET'])
def delete_stock(stock_id):
    Stock.get_by_ticker(stock_id).remove()

    return redirect(url_for('.index'))

api/src/templates/stocks/new_stock.jinja2
{% extends "base.jinja2" %}
{% block content %}
<h1>New page! No content yet</h1>
{% endblock %}

api/src/templates/stocks/stock.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="mt-3">
        <h1>{{ stock.ticker }} <small class="h4 text-muted">Summary statistics</small></h1>
    </div>
    <hr>
    <div class="container">
    <div class="row">
        <div class="col">
            <!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
  <div id="tradingview_fb2a4"></div>
  <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/symbols/NASDAQ-{{ stock.ticker }}/" rel="noopener" target="_blank"><span class="blue-text">{{ stock.ticker }} Chart</span></a> by TradingView</div>
  <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
  <script type="text/javascript">
  new TradingView.widget(
  {
  "width": 980,
  "height": 610,
  "symbol": "NASDAQ:{{ stock.ticker }}",
  "interval": "D",
  "timezone": "Etc/UTC",
  "theme": "dark",
  "style": "1",
  "locale": "en",
  "toolbar_bg": "#f1f3f6",
  "enable_publishing": false,
  "allow_symbol_change": true,
  "container_id": "tradingview_fb2a4"
}
  );
  </script>
</div>
<!-- TradingView Widget END -->
{#            <img src="https://www.google.com/finance/getchart?q={{ stock.ticker }}&p=10Y&i=86400" />#}
        </div>
        <div class="col align-self-center">
            <div class="row">
            <h5>Characteristics</h5>
            </div>
            <div class="row">
                <p>Expected Return: <strong>{{ 100*stock.mu |round(5) }}%</strong></p>
            </div>
            <div class="row">
                <p>Standard Deviation: <strong>{{ 100*stock.std |round(5) }}%</strong></p>
            </div>

        </div>
    </div>
    </div>
{% endblock %}

api/src/templates/stocks/stock_index.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="mt-3">
        <h1>Stocks <small class="h4 text-muted">list of available stocks</small></h1>
    </div>
    <hr>
    <div class="list-group">
        {% for stock in stocks %}
            <a href="{{ url_for('stocks.stock_page',stock_ticker = stock.ticker) }}" class="list-group-item list-group-item-action">
                <h4>{{ stock.ticker }}</h4>
                Expected Return: <strong>{{ stock.mu |round(5) }}</strong><br/>
                Standard Deviation: <strong>{{ stock.std |round(5) }}</strong><br/>
            </a>
        {% endfor %}
    </div>
    {% if session['email'] in config.ADMINS %}
        <a class="btn btn-success mt-3" href="{{ url_for('stocks.create_stock') }}" role="button">Create new</a>
    {% endif %}
{% endblock %}